apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: quang0072/ginjwt1-app:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: DB_USER
        - name: DB_PASSWORD
          value: DB_PASS
        - name: DB_NAME
          value: DB_NAME
        - name: SSLMODE
          value: disable
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000