version: '3.8'

services:
  ginpj2:
    build:
      context: .  # Building from the current directory
    container_name: ginjwt1-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=ginjwt1docker

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: ginjwt1docker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: