apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: quang0072/ginjwt1-app:latest 
        command: ["go", "run", "migrate/migrate.go"]
      restartPolicy: Never